language: go

sudo: false

go:
  - tip

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./cc-test-reporter after-build  -t gocov --exit-code $TRAVIS_TEST_RESULT
